spring.application.name=analytics

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# SQLite Configuration
spring.datasource.url=jdbc:sqlite:src/main/db/analytics.db
spring.datasource.driver-class-name=org.sqlite.JDBC
